// app/javascript/controllers/index.js
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'
import applicationController from './application_controller'
import StimulusReflex from 'stimulus_reflex'

// Manual imports (add new controllers here)
import HelloController from './hello_controller'

application.register('hello', HelloController)

// ✅ Initialize StimulusReflex
StimulusReflex.initialize(application, { applicationController, isolate: true })

StimulusReflex.debug = true
